### ISSUE TITLE
[Task] Need to fix the file / folder casing

### ISSUE THREAD

**Issue by mihnita** [oasis-tcs/xliff-xliff-22#26]
### Detailed Description

Some folders are use different case than the links to them.
This works on file systems that are not case sensitive (for example Windows, some MacOS disks)

But  merge fails on Linux and some MacOS disks (the macos disk initialization asks if you want a case sensitive file system or not).

So merge fails with:

```
modules/resourcedata/specification.xml
../../elements/resourcedata/resourceData.xml
java.io.FileNotFoundException: ~/third_party/xliff-22.mihnita/xliff-22/modules/resourcedata/../../elements/resourcedata/resourceData.xml (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
        at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
        at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:653)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:861)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:247)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
        at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
        at com.maxprograms.xml.Merger.parse(Unknown Source)
        at com.maxprograms.xml.Merger.recurse(Unknown Source)
        at com.maxprograms.xml.Merger.recurse(Unknown Source)
        at com.maxprograms.xml.Merger.parse(Unknown Source)
        at com.maxprograms.xml.Merger.recurse(Unknown Source)
        at com.maxprograms.xml.Merger.recurse(Unknown Source)
        at com.maxprograms.xml.Merger.run(Unknown Source)
        at com.maxprograms.xml.Merger.main(Unknown Source)
```

In `xliff-22/` we have:
* `./elements/resourceData`
* `./modules/resourcedata` (note the lowercase "d")
* `./attributes/resourceData`

But `modules/resourcedata/specification.xml` includes things from `./../elements/resourcedata/` (lowercase "d", the folder uses uppercase "D")

**Comment by mihnita** [comment]
### Complete report (`resourceData` folder only)

**References to `/elements/resourceData` (uppercase "D"):**

* `elements/resourceData/reference.xml`    [2]
* `elements/resourceData/res_target.xml`    [10]
* `elements/resourceData/resourceItem.xml`    [16]
* `elements/resourceData/res_source.xml`    [9]
* `elements/resourceData/resourceItemRef.xml`    [5]
* `modules/resourcedata/specification.xml`    [4]
* `modules/itsm/External_Resource.xml`    [2]

**References to `/elements/resourcedata` (lowercase "d"):**

* `elements/resourceData/reference.xml`    [2]
* `elements/resourceData/res_target.xml`    [2]
* `elements/resourceData/resourceItemRef.xml`    [1]
* `modules/resourcedata/specification.xml`    [20]
* `attributes/resourceData/res_resourceDataId.xml`    [2]
* `attributes/resourceData/res_context.xml`    [1]
* `attributes/resourceData/res_ref.xml`    [3]
* `attributes/resourceData/res_xml_lang.xml`    [3]
* `attributes/resourceData/res_id.xml`    [2]
* `attributes/resourceData/res_href.xml`    [1]
* `attributes/resourceData/res_mimeType.xml`    [1]

**References to `/attributes/resourceData` (uppercase "D"):**

* `elements/resourceData/reference.xml`    [3]
* `elements/resourceData/res_target.xml`    [5]
* `elements/resourceData/resourceItem.xml`    [7]
* `elements/resourceData/res_source.xml`    [6]
* `elements/resourceData/resourceItemRef.xml`    [3]
* `modules/resourcedata/specification.xml`    [12]

**References to `/attributes/resourcedata` (lowercase "d"):**

None

**References to `/modules/resourcedata` (lowercase "d"):**

None

**References to `/modules/resourceData` (uppercase "D"):**

None
